
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.1.23.147:8761/eureka/

#  instance:
#    instance-id: ${spring.application.name}:${random.int}
spring:
#  profiles:
#    active: node1
  application:
    name: xkw-api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
      gateway:
        routes:
        - id: route_qbm
          uri: http://localhost:8092
          predicates:
          - Path=/qbm/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10000
              redis-rate-limiter.burstCapacity: 10000
        - id: route_mdm
          uri: http://localhost:8093
          predicates:
          - Path=/mdm/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10000
              redis-rate-limiter.burstCapacity: 10000

#    添加对springcloud gateway的监控
management:
  endpoint:
    gateway:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8070
