server:
  port: 8093
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: gateway-admin
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/xkw_gateway?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.23.147:8761/eureka/

---
spring:
  profiles: product
  redis:
    host: 10.25.174.96
    database: 2
    port: 6379
    password: rzQP46/ThrECyHQ2tlEMSw==
    timeout: 5000ms
  datasource:
    url: jdbc:mysql://localhost:3306/xkw_gateway?useSSL=false&characterEncoding=utf-8
    username: xkw
    password: xkw.com1QAZ
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.27.13.142:8000/eureka/