server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.23.147:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xkw_gateway?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    gateway:
      routes:
      - id: gateway-entry
        uri: lb://xkw-api-gateway
        predicates:
        - Path=/**
        filters:
        - AddRequestHeader=X-Request-Foo, Basic QASsdafasdlfka;ASDFQwefds
  application:
    name: gateway-admin

