server:
  port: 8761

eureka:
  instance:
#    hostname: eureke-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
#  server:
#    enable-self-preservation: false
spring:
  application:
    name: eureke-server
